# General Settings
title: "Innovación tecnologica y empresarial"
email: "contacto@innovate.pe"
email_2: "support@tortoizthemes.com" #Por ver si va
description: >- # this means to ignore newlines until "baseurl:"
  Snowlake is a multi-concept and powerful site template contains 
  rich layouts with possibility of unlimited combinations & beautiful elements.

black_logo_1x: "/assets/images/logo.png"
black_logo_2x: "/assets/images/logo@2x.png"
light_logo_1x: "/assets/images/innovate_dark.png"
light_logo_2x: "/assets/images/logo_innovate_dark.png"

address_01: "Juan de Arona #755, Oficina 131 - Piso 2, San Isidro - Lima, Perú"
phone_number: "+51 972 597 233"
copyright_text: "© 2025 - Todos los derechos reservados."

google_analytics:
  enable: false
  key: "UA-664136761-1"  # UA-664136761-1

google_map: |
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3172.4564967931838!2d-122.03250858386237!3d37.33169997984258!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fb5b6e94ffe23%3A0x63bb79532baa6af4!2sApple+Campus!5e0!3m2!1sen!2str!4v1553850783971!5m2!1sen!2str" style="width:100%; height: 100%; border:0" allowfullscreen=""></iframe>

social_accounts:
  title: "Follow Us"
  links:
    - url: "#"
      icon: "jam jam-twitter"

    - url: "#"
      icon: "jam jam-facebook"

    - url: "#"
      icon: "jam jam-instagram"

    - url: "#"
      icon: "jam jam-vimeo"
      
    - url: "#"
      icon: "jam jam-youtube"


external_links:
  title: "Más información"
  links:
    - url: "#"
      text: "Inicio"
    - url: "#"
      text: "Nosotros"
    - url: "#"
      text: "Servicios"
    - url: "#"

external_links_02:
  title: "Need Help?"
  links:
    - url: "#"
      text: "Support"
    - url: "#"
      text: "Get Started"
    - url: "#"
      text: "Contact Us"
    - url: "#"
      text: "Terms of Use"
    - url: "#"
      text: "Privacy Policy"


external_links_03:
  title: "Company"
  links:
    - url: "#"
      text: "Our Team"
    - url: "#"
      text: "Strategy"
    - url: "#"
      text: "Service"
    - url: "#"
      text: "Mission"
    - url: "#"
      text: "Process"

one_page_nav_settings:
  links:
    - text: "Home"
      url: "#home"
    - text: "Services"
      url: "#services"
    - text: "Experiences"
      url: "#experiences"
    - text: "Portfolio"
      url: "#portfolio"
    - text: "Testimonials"
      url: "#testimonials"
    - text: "Contact"
      url: "#contact"

author_page_header:
  header_background_image: "/assets/images/art/bg31.jpg"

gallery:
  images:
  - img: "/assets/images/art/z1.svg"
  - img: "/assets/images/art/z2.svg"
  - img: "/assets/images/art/z3.svg"
  - img: "/assets/images/art/z4.svg"
  - img: "/assets/images/art/z5.svg"
  - img: "/assets/images/art/z6.svg"
  - img: "/assets/images/art/z7.svg"
  - img: "/assets/images/art/z8.svg"